export const CREATE_SCENARIO = 'CREATE_SCENARIO';
export const REQUEST_SCENARIOS = 'REQUEST_SCENARIOS';
export const REQUEST_SCENARIO = 'REQUEST_SCENARIO';
export const UPDATE_SCENARIO = 'UPDATE_SCENARIO';
export const DESTROY_SCENARIO = 'DESTROY_SCENARIO';

export const MOVE_SCENARIO = 'MOVE_SCENARIO';
export const REORDER_SCENARIOS = 'REORDER_SCENARIOS';

export const CREATE_STAGE = 'CREATE_STAGE';
export const REQUEST_SCENARIO_STAGES = 'REQUEST_SCENARIO_STAGES';
export const REQUEST_STAGE = 'REQUEST_STAGE';
export const UPDATE_STAGE = 'UPDATE_STAGE';
export const DESTROY_STAGE = 'DESTROY_STAGE';
