export const CREATE_SCENARIO = 'CREATE_SCENARIO';
export const REQUEST_SCENARIOS = 'REQUEST_SCENARIOS';
export const REQUEST_SCENARIO = 'REQUEST_SCENARIO';
export const UPDATE_SCENARIO = 'UPDATE_SCENARIO';
export const DESTROY_SCENARIO = 'DESTROY_SCENARIO';

export const MOVE_SCENARIO = 'MOVE_SCENARIO';
export const REORDER_SCENARIOS = 'REORDER_SCENARIOS';
