export const CREATE_SCENARIO = 'CREATE_SCENARIO';
export const REQUEST_SCENARIOS = 'FETCH_STORED_SCENARIOS';
export const UPDATE_SCENARIO = 'UPDATE_STORED_SCENARIO';
export const DESTROY_SCENARIO = 'DESTROY_SCENARIO';

export const MOVE_SCENARIO = 'MOVE_SCENARIO';
export const REORDER_SCENARIOS = 'REORDER_SCENARIOS';
