export const APPLY_STORED_SCENARIOS = 'APPLY_STORED_SCENARIOS';
export const ADD_STORED_SCENARIO = 'ADD_STORED_SCENARIO';
export const UPDATE_STORED_SCENARIO = 'UPDATE_STORED_SCENARIO';
export const REMOVE_STORED_SCENARIO = 'REMOVE_STORED_SCENARIO';
export const MOVE_STORED_SCENARIO = 'MOVE_STORED_SCENARIO';
export const SWITCH_STORED_SCENARIO_STATE = 'SWITCH_STORED_SCENARIO_STATE';
export const UPDATE_STORED_SCENARIO_CACHE = 'UPDATE_STORED_SCENARIO_CACHE';


export const ADD_NEW_SCENARIO = 'ADD_NEW_SCENARIO';
export const REMOVE_NEW_SCENARIO = 'REMOVE_NEW_SCENARIO';
export const UPDATE_NEW_SCENARIO_CACHE = 'UPDATE_NEW_SCENARIO_CACHE';
