export const ADD_OR_UPDATE_STORED_SCENARIO = 'ADD_OR_UPDATE_STORED_SCENARIO';
export const REMOVE_STORED_SCENARIO = 'REMOVE_STORED_SCENARIO';
export const SWITCH_STORED_SCENARIO_STATE = 'SWITCH_STORED_SCENARIO_STATE';
export const UPDATE_STORED_SCENARIO_CACHE = 'UPDATE_STORED_SCENARIO_CACHE';

export const ADD_NEW_SCENARIO = 'ADD_NEW_SCENARIO';
export const REMOVE_NEW_SCENARIO = 'REMOVE_NEW_SCENARIO';
export const UPDATE_NEW_SCENARIO_CACHE = 'UPDATE_NEW_SCENARIO_CACHE';

export const ADD_OR_UPDATE_STORED_STAGE = 'ADD_OR_UPDATE_STORED_STAGE';
export const REMOVE_STORED_STAGE = 'REMOVE_STORED_STAGE';
export const SWITCH_STORED_STAGE_STATE = 'SWITCH_STORED_STAGE_STATE';
export const UPDATE_STORED_STAGE_CACHE = 'UPDATE_STORED_STAGE_CACHE';

export const ADD_NEW_STAGE = 'ADD_NEW_STAGE';
export const REMOVE_NEW_STAGE = 'REMOVE_NEW_STAGE';
export const UPDATE_NEW_STAGE_CACHE = 'UPDATE_NEW_STAGE_CACHE';

export const ADD_OR_UPDATE_STORED_SCENE = 'ADD_OR_UPDATE_STORED_SCENE';
export const REMOVE_STORED_SCENE = 'REMOVE_STORED_SCENE';
export const SWITCH_STORED_SCENE_STATE = 'SWITCH_STORED_SCENE_STATE';
export const UPDATE_STORED_SCENE_CACHE = 'UPDATE_STORED_SCENE_CACHE';

export const ADD_NEW_SCENE = 'ADD_NEW_SCENE';
export const REMOVE_NEW_SCENE = 'REMOVE_NEW_SCENE';
export const UPDATE_NEW_SCENE_CACHE = 'UPDATE_NEW_SCENE_CACHE';
