export const RECEIVE_SCENARIO_LIST = 'RECEIVE_SCENARIO_LIST';
export const UPDATE_SCENARIO = 'UPDATE_SCENARIO';
export const ADD_SCENARIO = 'ADD_SCENARIO';
export const ERASE_SCENARIO = 'ERASE_SCENARIO';
export const MOVE_SCENARIO = 'MOVE_SCENARIO';
